version: "3.7"
services:
  php-fpm:
    build:
      context: ./
      dockerfile: Dockerfile
    image: laravel-php-fpm
    container_name: "${APP_NAME}-php-fpm"
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ${APP_FOLDER}:/var/www
    networks:
      - laravel
    extra_hosts:
      - "host.docker.internal:host-gateway"
    # command: /bin/sh /laravel_run_up.sh

  nginx:
    image: nginx:alpine
    container_name: ${APP_NAME}-nginx
    restart: unless-stopped
    ports:
      - "${APP_PORT}:80"
    volumes:
      - ${APP_FOLDER}:/var/www
      - ./nginx:/etc/nginx/templates/
    environment:
      - NGINX_UP_STREAM=${APP_NAME}-php-fpm:9000
    networks:
      - laravel

networks:
  laravel:
    driver: bridge